// components/CharacterDisplay.tsx
import Select from 'react-select'
import ImageLoader from './ImageLoader'
import customStyles from './CharacterSelectStyles'
import style from './CustomStyle.module.css'
import { CharacterState } from '../const/character'
import getCharacters from '../utils/GetCharacters'

export default function CharacterDisplay({ id, characterState, setCharacterState, tw, th, textColor, textSize, marginLeft, transparent, shadowSize, shadowColor }) {
  return (
    <div className={style.container} style={{
      width: tw,
      height: th,
      marginLeft: marginLeft
    }}>
      <div className={style.image}>
        <ImageLoader imageName={characterState[id].value} />
      </div>
      <div className='character'>
        <Select
          id='long-value-select' instanceId='long-value-select'
          styles={customStyles({ textColor, textSize, shadowSize, shadowColor, transparent })}
          value={{ value: characterState[id].value, label: characterState[id].label }}
          onChange={(param) => setCharacterState(characterState.map((ch: CharacterState) => ch.id === id ? { ...ch, label: param!.label, value: param!.value } : { ...ch }))}
          options={getCharacters(characterState)}
        />
      </div>
    </div>
  )
}

// src/routes/CharacterDisplay.svelte
<script lang="ts">
	import Select from 'svelte-select';
	import type { CharacterState } from '../const/character';
	import { getCharacters } from '$lib/utils';

	export let id: string;
	export let characterState: CharacterState[];
	export let textColor: string;
	export let textSize: number;
	export let marginLeft: string;
	export let transparent: boolean;
	export let shadowSize: string;
	export let shadowColor: string;

	function setImage(event: CustomEvent) {
		const props = event.detail as CharacterState;
		img = `/assets/${props.value}`;
		alt = props.label;
	}

	const style = `font-weight:bold; font-size:${textSize}px; color:${transparent ? 'transparent' : textColor};`;

	let img = '/assets/loading.gif';
	let alt = 'alt';
</script>

<div style="width: 200px; height:250px; marginLeft: {marginLeft}">
	<img src={img} {alt} width="100%" height="100%" />
	<Select
		items={getCharacters(characterState)}
		clearable={false}
		inputStyles={style}
		containerStyles={style}
		on:change={setImage}
	/>
</div>
